version: "3.1"

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: on-failure
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: samuel
      MYSQL_PASSWORD: samuel


    volumes:
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    links:
      - mysql:db
    ports:
      - 8080:8080


  config-server:
    image: samfrosh/config-server
    container_name: config-server
    restart: on-failure
    hostname: config-server
    environment:
      EUREKA_HOST: eureka-server
      ZIPKIN_HOST: zipkin
      CONFIG_SERVER_HOST: config-server
    depends_on:
      - zipkin
    networks:
      - spring
    ports:
      - "8081:8081"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: on-failure
    networks:
      - spring
    ports:
      - "9411:9411"

  mail-server:
    image: maildev/maildev
    container_name: maildev
    restart: on-failure
    networks:
     - spring
    ports:
     - "1080:1080"
     - "1025:1025"

  eureka-server:
    image: samfrosh/eureka-server
    container_name: eureka-server
    restart: on-failure
    hostname: eureka-server
    networks:
      - spring
    ports:
      - "8761:8761"
    environment:
      EUREKA_HOST: eureka-server
      ZIPKIN_HOST: zipkin
      CONFIG_SERVER_HOST: config-server
    depends_on:
      - zipkin
      - config-server



networks:
  mysql:
    driver: bridge
  spring:
    driver: bridge

