version: "3.9"

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: on-failure
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_USER: samuel
      MYSQL_PASSWORD: samuel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twitter

  config-server:
    image: config-server
    container_name: config-server
    restart: on-failure
    hostname: config-server
    environment:
      EUREKA_HOST: eureka-server
      ZIPKIN_HOST: zipkin
      CONFIG_SERVER_HOST: config-server
    depends_on:
      - zipkin
    networks:
      - spring
    ports:
      - "8081:8081"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: on-failure
    networks:
      - spring
    ports:
      - "9411:9411"

  eureka-server:
    image: eureka-service
    container_name: eureka-server
    restart: on-failure
    hostname: eureka-server
    networks:
      - spring
    ports:
      - "8761:8761"
    environment:
      EUREKA_HOST: eureka-server
      ZIPKIN_HOST: zipkin
      CONFIG_SERVER_HOST: config-server
    depends_on:
      - zipkin
      - config-server


networks:
  mysql:
    driver: bridge
  spring:
    driver: bridge

