spring:
  application:
    name: apgw

  cloud:
    gateway:

      globalcors:
        corsConfigurations:
          '[/API/V1/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/API/V1/USERS/**

  config:
    import: "optional:configserver:http://localhost:8081"
