spring:
  application:
    name: apgw

  cloud:
    gateway:

      globalcors:
        corsConfigurations:
          '[/API/V1/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/API/V1/USERS/**

  config:
    import: "optional:configserver:http://localhost:8081"
