server:
  port: 8082

eureka:
  instance:
    hostname: localhost

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_HOST_URL_DEFAULTZONE}


management:
  tracing:
    sampling:
      probability: 1.0
