server:
  port: 8082

eureka:
  instance:
    hostname: localhost

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.110.1:8761/eureka


management:
  tracing:
    sampling:
      probability: 1.0
