server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_HOST_URL_DEFAULTZONE}


management:
  tracing:
    sampling:
      probability: 1.0