server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka


management:
  tracing:
    sampling:
      probability: 1.0