spring:

  flyway:
    validate-on-migrate: false
    out-of-order: true
    locations: classpath:db/migration

  datasource:
    url: jdbc:mysql://localhost:3309/user
    username: samuel
    password: samuel
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_HOST_URL_DEFAULTZONE}

management:
  tracing:
    sampling:
      probability: 1.0